### ISSUE TITLE
Cannot activate

### ISSUE THREAD

**Issue by marcoskirsch** [ArnaudHocevar/ZPGoogleAnalytics#3]
First time I install a ZenPhoto extension so I will describe how I did it - I was not able to find instructions in ZPGoogleAnalytics:
a) copied google_analytics.php to zp-core/zp-extensions
b) copied google_analytics folder to plugins/

After this, the plugin shows up in <my gallery>/zp-core/admin-plugins.php?page=plugins&tab=misc
When I select the checkbox and hit Apply, I get a message that says "Applied" but the plug in shows up with the checkbox deselected. Upon inspection of the HTML my gallery returns, I see no Google Analytics tracking code.

Did I do something wrong? Any ideas on how to debug/fix this?

Thanks!

**Comment by marcoskirsch** [comment]
Ok, after some research I noticed my installation was wrong. Everything goes into plugins/
My bad, rookie mistake.
After fixing this and clearing out the settings stored in the DB I started over. I had to scratch my head quite a bit to notice that if I was logged in to the zen photo installation, the snippet is not inserted! I would have hoped for a little HTML comment at the least!

In any case, fixed: user error

**Comment by ArnaudHocevar** [comment]
Good to know you did not face an application bug.

For the issue where the snippet is not shown when you are logged in, you have to tick the _Enable Admin tracking_ tickbox.

If you think a message should be displayed somewhere on the page to display the status of the plug-in, feel free to open a new enhancement request.

**Comment by marcoskirsch** [comment]
Well, there is still the checkbox issue, that still looks like a bug. I'll post about it separately.
